name: Build and Run Phonebook C Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile with GCC
        run: gcc phonebook.c -o phonebook.exe
        shell: cmd

      - name: Success message
        run: echo Build Successful!
        shell: cmd
