name: Build and Run Phonebook C Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MinGW
        uses: msys2/setup-msys2@v2
        with:
          install: mingw-w64-x86_64-gcc

      - name: Compile C code
        shell: msys2 {0}
        run: gcc phonebook.c -o phonebook.exe

      - name: Success
        shell: msys2 {0}
        run: echo "Build Successful!"
