name: Build and Run Phonebook C Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GCC via Chocolatey
        run: choco install mingw -y
        shell: powershell

      - name: Add MinGW to PATH
        run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH
        shell: powershell

      - name: Compile C code
        run: C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin\gcc.exe phonebook.c -o phonebook.exe
        shell: powershell

      - name: Success
        run: echo "Build Successful!"
        shell: powershell
